[[check]]
type   = "Exclude"
category = "Infinite"
scope  = "all"
[[check]]
type   = "Exclude"
category = "Partial"
scope  = "all"

[[check]]
type   = "Exclude"
id = "STAN-0213"
scope  = "all"
[[check]]
type   = "Exclude"
id = "STAN-0206"
scope  = "all"
[[check]]
type   = "Exclude"
id = "STAN-0208"
scope  = "all"
[[check]]
type   = "Exclude"
id = "STAN-0207"
scope  = "all"
