name: frugel
version: 0.0.2.0
github: "cdfa/frugel"
license: GPL-3
author: "Colin de Roos"
maintainer: "colinderoos[at]gmail[dot]com"
copyright: "2021 Colin de Roos"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: A frugal projectional editor for Live Programming

dependencies:
  - relude >= 1.0.0.0

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -fhide-source-paths
  - -fno-show-valid-hole-fits # Until https://gitlab.haskell.org/ghc/ghc/-/issues/16875 is resolved
  - -j

default-extensions:
  - OverloadedStrings
  - OverloadedLabels
  - DisambiguateRecordFields
  - DeriveGeneric

library:
  source-dirs: src
  when:
    - condition: impl(ghcjs)
      then:
        dependencies: base-noprelude-ghcjs >= 4.7 && < 5
      else:
        dependencies: base-noprelude >= 4.7 && < 5
  # Note: you may need to stack build before changes are reflected in the editor, because we use a cabal cradle for this component, because stack repl does not support internal libraries https://github.com/commercialhaskell/stack/issues/4564
  dependencies:
    - prettyprinter ^>= 1.7.0
    - composition
    - optics ^>= 0.4
    - optics-vl ^>= 0.2.1
    - lens
    - mtl

internal-libraries:
  scout:
    when:
      - condition: impl(ghcjs)
        then:
          dependencies: base-noprelude-ghcjs >= 4.7 && < 5
        else:
          dependencies: base-noprelude >= 4.7 && < 5
      - condition: false # Work around hpack issue https://github.com/sol/hpack/issues/303
        other-modules: Paths_frugel
    source-dirs: scout-src
    other-modules: BasicEvaluation
    dependencies:
      - frugel
      - megaparsec ^>= 9.0.1
      - parser-combinators
      - containers
      - prettyprinter ^>= 1.7.0
      - composition
      - it-has
      - optics ^>= 0.4
      - lens
      - mtl
      - multiset
      - genvalidity
      - validity-text
      - validity-containers
      - genvalidity-text
      - genvalidity-containers
      - QuickCheck
      - testing-feat
      - size-based
      - dictionary-sharing
      - generic-data ^>= 0.8.0.0
      - Interpolation
      # Until https://github.com/well-typed/optics/pull/430/files# is merged
      - optics-core ^>= 0.4
      - profunctors
      - indexed-profunctors

executables:
  frugel-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=--nonmoving-gc -A16M -M1G -N -Mgrace=16M"'
      - -feager-blackholing
    ghcjs-options:
      - -dedupe
      - '"-with-rtsopts=--nonmoving-gc -N"' # sadly, it seems no heap overflow exceptions are thrown when the heap is limitied with ghcjs
    dependencies:
      - frugel
      - scout
      - miso ^>= 1.8.0.0
      - pretty-show
      - prettyprinter ^>= 1.7.0
      - aeson
      - QuickCheck
      - multiset
      - composition
      - lens
      - Interpolation
    when:
      - condition: impl(ghcjs)
        then:
          dependencies: base-noprelude-ghcjs >= 4.7 && < 5
        else:
          dependencies:
            - base-noprelude >= 4.7 && < 5
            - jsaddle ^>= 0.9.8
            - jsaddle-warp ^>= 0.9
            - websockets ^>= 0.12.7
            - warp ^>= 3.3.17
            - wai-app-static ^>= 3.1.7
      - condition: false # Work around hpack issue https://github.com/sol/hpack/issues/303
        other-modules: Paths_frugel

tests:
  frugel-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base-noprelude >= 4.7 && < 5
      - containers
      - frugel
      - scout
      - QuickCheck
      - genvalidity
      - genvalidity-containers
      - sydtest
      - genvalidity-sydtest
      - multiset
    when:
      - condition: impl(ghcjs)
        buildable: false
      - condition: false # Work around hpack issue https://github.com/sol/hpack/issues/303
        other-modules: Paths_frugel
