name: frugel
version: 0.0.1
github: "cdfa/frugel"
license: GPL-3
author: "Colin de Roos"
maintainer: "colinderoos[at]gmail[dot]com"
copyright: "2021 Colin de Roos"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: A frugal projectional editor for Live Programming

dependencies:
  - base-noprelude >= 4.7 && < 5
  - relude >= 0.7.0.0

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -fhide-source-paths

default-extensions:
  - OverloadedStrings
  - OverloadedLabels
  - DisambiguateRecordFields
  - DeriveGeneric

library:
  source-dirs: src
  when:
    - condition: "impl(ghcjs)"
      source-dirs: scout-src
      exposed-modules: Scout
  # Note: you may need to stack build before changes are reflected in the editor, because we use a cabal cradle for this component, because stack does not support internal libraries https://github.com/commercialhaskell/stack/issues/4564
  dependencies:
    - megaparsec >= 9.0.1
    - parser-combinators
    - containers
    - text
    - prettyprinter >= 1.7.0
    - composition
    - it-has
    - optics >= 0.3
    - optics-vl >= 0.2.1
    - lens
    - mtl
    - multiset
    - genvalidity
    - validity-text
    - validity-containers
    - genvalidity-text
    - genvalidity-containers
    - QuickCheck
    - testing-feat
    - size-based
    - dictionary-sharing


internal-libraries:
  scout:
    when: # Ugly hack because ghcjs does not seem to support internal libraries: https://github.com/ghcjs/ghcjs/issues/806
      - condition: "impl(ghcjs)"
        buildable: false
      - condition: false # Work around hpack issue https://github.com/sol/hpack/issues/303
        other-modules: Paths_frugel
    source-dirs: scout-src
    exposed-modules: Scout
    dependencies:
      - frugel
      - megaparsec >= 9.0.1
      - parser-combinators
      - containers
      - text
      - prettyprinter >= 1.7.0
      - composition
      - it-has
      - optics >= 0.3
      - lens
      - mtl
      - multiset
      - genvalidity
      - validity-text
      - validity-containers
      - genvalidity-text
      - genvalidity-containers
      - QuickCheck
      - size-based

executables:
  frugel-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - frugel
      - miso
      - pretty-show
      - prettyprinter >= 1.7.0
      - aeson
      - QuickCheck
    when:
      - condition: "!impl(ghcjs)"
        dependencies:
          - jsaddle-warp
          - scout
      - condition: false # Work around hpack issue https://github.com/sol/hpack/issues/303
        other-modules: Paths_frugel

tests:
  frugel-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - frugel
      - sydtest
      - genvalidity-sydtest
      - multiset
    when:
      - condition: "!impl(ghcjs)"
        dependencies: scout
      - condition: false # Work around hpack issue https://github.com/sol/hpack/issues/303
        other-modules: Paths_frugel
