name: frugel
version: 0.0.1
github: "cdfa/frugel"
license: GPL-3
author: "Colin de Roos"
maintainer: "colinderoos[at]gmail[dot]com"
copyright: "2021 Colin de Roos"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: A frugal projectional editor for Live Programming

dependencies:
  - base-noprelude >= 4.7 && < 5
  - relude

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -fhide-source-paths

library:
  source-dirs: src
  dependencies:
    - miso

executables:
  frugel-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - frugel
      - miso
    when:
      - condition: "!impl(ghcjs)"
        dependencies: jsaddle-warp

tests:
  frugel-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - frugel
